#!/bin/bash
####################################
# Since 1999 Colorizing Shells
# By: isca <isca at isca dot space
#
# Version 0.4
###################################

#Export by default
set -a

clean="\033[0m"
green="\033[32;40m"
red="\033[31;40m"
blue="\033[34;40m"
yellow="\033[33;40m"
cyan="\033[36;40m"
pink="\033[35;40m"
whiteb="\033[37;1m"

